const { createClient } = require('@supabase/supabase-js');
require('dotenv').config();
const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_KEY);

const FACTURAS = [
  { fecha_factura:'2026-06-01', proveedor:'Macaque Consulting, SL', referencia:'F260107', concepto:'Consultoría mensual Gulliver AI', importe:3751.00, sociedad_codigo:'g', estado:'pendiente' },
  { fecha_factura:'2026-05-01', proveedor:'Macaque Consulting, SL', referencia:'F260086', concepto:'Consultoría vencida 30/05', importe:3751.00, sociedad_codigo:'g', estado:'alerta', alerta_texto:'Vencida 30/05/2026 sin pagar', fecha_vencimiento:'2026-05-30' },
  { fecha_factura:'2026-05-01', proveedor:'Macaque Consulting, SL', referencia:'F260064', concepto:'Consultoría vencida 30/04', importe:3932.51, sociedad_codigo:'g', estado:'alerta', alerta_texto:'Vencida 30/04/2026 sin pagar', fecha_vencimiento:'2026-04-30' },
  { fecha_factura:'2026-04-01', proveedor:'Macaque Consulting, SL', referencia:'F260063', concepto:'Consultoría vencida 30/04', importe:3751.00, sociedad_codigo:'g', estado:'alerta', alerta_texto:'Vencida 30/04/2026 sin pagar', fecha_vencimiento:'2026-04-30' },
  { fecha_factura:'2026-06-03', proveedor:'Refineria Web, SL', referencia:'F148087', concepto:'Servicios web Gulliver', importe:1105.34, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2026-06-10', proveedor:'Refineria Web, SL', referencia:'F148126', concepto:'Servicios FunnelsHotel Apper', importe:626.18, sociedad_codigo:'a', estado:'procesada' },
  { fecha_factura:'2026-06-11', proveedor:'Refineria Web, SL', referencia:'F148129', concepto:'Servicios Gulliver', importe:653.40, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2026-06-01', proveedor:'Anthropic, PBC', referencia:'ANT-JUN26', concepto:'Claude API junio', importe:null, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2026-06-10', proveedor:'OpenAI ChatGPT Business', referencia:'GPT-BIZ-JUN26', concepto:'ChatGPT Business 3 seats', importe:null, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2026-06-01', proveedor:'OpenAI API', referencia:'API-JUN26', concepto:'OpenAI API credits $5.06', importe:5.06, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2026-06-17', proveedor:'B2B Hosting', referencia:'24168', concepto:'Hosting Apper Street vence 25/06', importe:null, sociedad_codigo:'a', estado:'alerta', alerta_texto:'Vence 25/06/2026', fecha_vencimiento:'2026-06-25' },
  { fecha_factura:'2026-06-15', proveedor:'HighLevel Inc.', referencia:'2252-8804', concepto:'GoHighLevel SaaS', importe:null, sociedad_codigo:'s', estado:'procesada' },
  { fecha_factura:'2026-06-17', proveedor:'Webempresa', referencia:'F26-73369', concepto:'Dominio sanchotapasbar.com', importe:16.99, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2026-06-10', proveedor:'Vercel Inc.', referencia:'2114-4670', concepto:'Hosting Vercel', importe:null, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2026-06-07', proveedor:'Elfsight (Paddle)', referencia:'ELF-JUN26', concepto:'All Apps Pack', importe:72.00, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2026-06-11', proveedor:'Xisco Monserrat', referencia:'XIS-2686', concepto:'Grabación Hotel Zafiro', importe:null, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2026-06-11', proveedor:'Iria Méndez', referencia:'IRI-JUN26', concepto:'Shooting Hotel Zafiro', importe:null, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2026-06-01', proveedor:'Euromoto Palma', referencia:'ALQ-000086', concepto:'Alquiler oficina junio', importe:null, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2026-06-10', proveedor:'Wayco Ruzafa', referencia:'2026-WRF18917', concepto:'Cobro fallido 3 avisos', importe:null, sociedad_codigo:'x', estado:'alerta', alerta_texto:'Cobro fallido reiterado 3 avisos' },
  { fecha_factura:'2026-06-01', proveedor:'Pedro Béjar — Agesbal', referencia:'PED-JUN26', concepto:'Asesoría fiscal junio', importe:null, sociedad_codigo:'x', estado:'procesada' },
  { fecha_factura:'2025-12-30', proveedor:'Macaque Consulting, SL', referencia:'F250130', concepto:'Consultoría O2DOSMAD Design', importe:1815.00, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2026-06-03', proveedor:'Refineria Web, SL', referencia:'RINV-2026-00092', concepto:'Factura rectificativa O2Dosmad', importe:1105.34, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2026-05-01', proveedor:'Refineria Web, SL', referencia:'F147985', concepto:'Servicios O2Dosmad Design', importe:1105.34, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2026-05-01', proveedor:'Refineria Web, SL', referencia:'F147986', concepto:'Servicios Apper Street', importe:2123.55, sociedad_codigo:'a', estado:'procesada' },
  { fecha_factura:'2026-05-01', proveedor:'Refineria Web, SL', referencia:'RINV-2026-00082', concepto:'Rectificativa Apper Street', importe:2123.55, sociedad_codigo:'a', estado:'procesada' },
  { fecha_factura:'2026-05-01', proveedor:'Refineria Web, SL', referencia:'F147993', concepto:'Servicios Apper Street', importe:2123.55, sociedad_codigo:'a', estado:'procesada' },
  { fecha_factura:'2026-04-29', proveedor:'Anthropic, PBC', referencia:'ANT-APR26', concepto:'Claude API abril', importe:null, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2026-04-01', proveedor:'Anthropic, PBC', referencia:'ANT-APR26b', concepto:'Claude API abril', importe:null, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2026-05-10', proveedor:'OpenAI ChatGPT Business', referencia:'GPT-BIZ-MAY26', concepto:'ChatGPT Business 3 seats mayo', importe:null, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2026-04-10', proveedor:'OpenAI ChatGPT Business', referencia:'GPT-BIZ-APR26', concepto:'ChatGPT Business 3 seats abril', importe:null, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2026-02-10', proveedor:'OpenAI ChatGPT Business', referencia:'GPT-BIZ-FEB26', concepto:'ChatGPT Business 3 seats febrero', importe:null, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2026-01-10', proveedor:'OpenAI ChatGPT Business', referencia:'GPT-BIZ-ENE26', concepto:'ChatGPT Business 3 seats enero', importe:null, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2025-11-10', proveedor:'OpenAI ChatGPT Business', referencia:'GPT-BIZ-NOV25', concepto:'ChatGPT Business 3 seats noviembre', importe:null, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2025-10-10', proveedor:'OpenAI ChatGPT Business', referencia:'GPT-BIZ-OCT25', concepto:'ChatGPT Business 3 seats octubre', importe:null, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2025-12-01', proveedor:'OpenAI API', referencia:'API-DIC25a', concepto:'OpenAI API credits $5.03', importe:5.03, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2025-12-01', proveedor:'OpenAI API', referencia:'API-DIC25b', concepto:'OpenAI API credits $5.02', importe:5.02, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2025-11-01', proveedor:'OpenAI API', referencia:'API-NOV25a', concepto:'OpenAI API credits $5.22', importe:5.22, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2025-11-01', proveedor:'OpenAI API', referencia:'API-NOV25b', concepto:'OpenAI API credits $5.02', importe:5.02, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2025-10-01', proveedor:'OpenAI API', referencia:'API-OCT25', concepto:'OpenAI API credits $5.04', importe:5.04, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2025-09-01', proveedor:'OpenAI API', referencia:'API-SEP25a', concepto:'OpenAI API credits $5.49', importe:5.49, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2025-09-01', proveedor:'OpenAI API', referencia:'API-SEP25b', concepto:'OpenAI API credits $5.48', importe:5.48, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2025-09-01', proveedor:'OpenAI API', referencia:'API-SEP25c', concepto:'OpenAI API credits $5.08', importe:5.08, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2025-08-01', proveedor:'OpenAI API', referencia:'API-AGO25a', concepto:'OpenAI API credits $5.71', importe:5.71, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2025-08-01', proveedor:'OpenAI API', referencia:'API-AGO25b', concepto:'OpenAI API credits $5.22', importe:5.22, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2025-08-01', proveedor:'OpenAI API', referencia:'API-AGO25c', concepto:'OpenAI API credits $5.80', importe:5.80, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2025-08-01', proveedor:'OpenAI API', referencia:'API-AGO25d', concepto:'OpenAI API credits $5.55', importe:5.55, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2025-07-01', proveedor:'OpenAI API', referencia:'API-JUL25a', concepto:'OpenAI API credits $5.06', importe:5.06, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2025-07-01', proveedor:'OpenAI API', referencia:'API-JUL25b', concepto:'OpenAI API credits $5.03', importe:5.03, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2025-06-01', proveedor:'OpenAI API', referencia:'API-JUN25a', concepto:'OpenAI API credits $5.02', importe:5.02, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2025-06-01', proveedor:'OpenAI API', referencia:'API-JUN25b', concepto:'OpenAI API credits $5.06', importe:5.06, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2025-05-01', proveedor:'OpenAI API', referencia:'API-MAY25a', concepto:'OpenAI API credits $5.19', importe:5.19, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2025-05-01', proveedor:'OpenAI API', referencia:'API-MAY25b', concepto:'OpenAI API credits $5.15', importe:5.15, sociedad_codigo:'g', estado:'procesada' },
  { fecha_factura:'2026-06-03', proveedor:'B2B Hosting', referencia:'24152', concepto:'Hosting O2DOSMAD Design', importe:null, sociedad_codigo:'d', estado:'pendiente' },
  { fecha_factura:'2026-05-03', proveedor:'B2B Hosting', referencia:'23878', concepto:'Hosting O2DOSMAD mayo', importe:null, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2025-12-05', proveedor:'B2B Hosting', referencia:'22428', concepto:'Hosting Apper Street', importe:185.13, sociedad_codigo:'a', estado:'procesada' },
  { fecha_factura:'2025-12-12', proveedor:'B2B Hosting', referencia:'22460', concepto:'Hosting Apper Street', importe:114.95, sociedad_codigo:'a', estado:'procesada' },
  { fecha_factura:'2026-06-01', proveedor:'HighLevel Inc.', referencia:'2223-3373', concepto:'GoHighLevel SaaS junio', importe:null, sociedad_codigo:'s', estado:'procesada' },
  { fecha_factura:'2026-05-01', proveedor:'HighLevel Inc.', referencia:'2680-8720', concepto:'GoHighLevel SaaS mayo', importe:null, sociedad_codigo:'s', estado:'procesada' },
  { fecha_factura:'2026-05-01', proveedor:'HighLevel Inc.', referencia:'2122-2571', concepto:'GoHighLevel SaaS mayo', importe:null, sociedad_codigo:'s', estado:'procesada' },
  { fecha_factura:'2025-12-24', proveedor:'HighLevel Inc.', referencia:'2610-2052', concepto:'GoHighLevel SaaS diciembre', importe:null, sociedad_codigo:'s', estado:'procesada' },
  { fecha_factura:'2026-06-05', proveedor:'Webempresa', referencia:'F26-69285', concepto:'Dominio clinicacapilargalvezrabadan.com', importe:16.99, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2026-06-03', proveedor:'Webempresa', referencia:'F26-68556', concepto:'Dominio sushikosbi.es', importe:15.99, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2026-05-29', proveedor:'Webempresa', referencia:'F26-66736', concepto:'Dominio pizzeriaenpetra.com', importe:16.99, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2026-05-29', proveedor:'Webempresa', referencia:'F26-66735', concepto:'Dominio pizzeriadepetra.com', importe:16.99, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2026-05-29', proveedor:'Webempresa', referencia:'F26-66734', concepto:'Dominio pizzeriapetra.com', importe:16.99, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2026-04-27', proveedor:'Webempresa', referencia:'F26-54756', concepto:'Dominio bonthai.es', importe:15.99, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2025-12-23', proveedor:'Webempresa', referencia:'F25-137411', concepto:'Dominio lapetrezze.com', importe:16.99, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2025-12-15', proveedor:'Webempresa', referencia:'F25-134810', concepto:'Dominio mezzamorrisdelivery.es', importe:15.99, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2025-12-15', proveedor:'Webempresa', referencia:'F25-134804', concepto:'Dominio ferrettidelivery.es', importe:15.99, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2025-12-24', proveedor:'Apple Services', referencia:'APPLE-DIC25a', concepto:'iCloud+ 200GB mensual', importe:2.99, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2025-12-23', proveedor:'Apple Services', referencia:'APPLE-DIC25b', concepto:'Apple TV + servicios', importe:11.99, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2026-05-07', proveedor:'Elfsight (Paddle)', referencia:'ELF-MAY26', concepto:'All Apps Pack mayo', importe:72.00, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2026-05-01', proveedor:'DinoRANK', referencia:'FA-29604', concepto:'Suscripción SEO mayo', importe:15.00, sociedad_codigo:'s', estado:'procesada' },
  { fecha_factura:'2025-12-01', proveedor:'DinoRANK', referencia:'FA-27127', concepto:'Suscripción SEO diciembre', importe:15.00, sociedad_codigo:'s', estado:'procesada' },
  { fecha_factura:'2025-12-23', proveedor:'MeetGeek.ai', referencia:'MEE-2604-7658', concepto:'MeetGeek Business', importe:null, sociedad_codigo:'s', estado:'procesada' },
  { fecha_factura:'2025-12-17', proveedor:'Google', referencia:'GOO-DIC25', concepto:'Google Play 9,99€', importe:9.99, sociedad_codigo:'s', estado:'procesada' },
  { fecha_factura:'2026-06-01', proveedor:'BSB La Teva Assessoria', referencia:'BSB-JUN26', concepto:'Gestoría mayo 2026', importe:null, sociedad_codigo:'x', estado:'procesada' },
  { fecha_factura:'2026-05-01', proveedor:'Pedro Béjar — Agesbal', referencia:'PED-MAY26', concepto:'Asesoría fiscal mayo', importe:null, sociedad_codigo:'x', estado:'procesada' },
  { fecha_factura:'2026-04-01', proveedor:'Pedro Béjar — Agesbal', referencia:'PED-ABR26', concepto:'Asesoría fiscal abril', importe:null, sociedad_codigo:'x', estado:'procesada' },
  { fecha_factura:'2025-12-01', proveedor:'Pedro Béjar — Agesbal', referencia:'PED-DIC25', concepto:'Asesoría fiscal diciembre', importe:null, sociedad_codigo:'x', estado:'procesada' },
  { fecha_factura:'2026-06-01', proveedor:'Xisco Monserrat', referencia:'XIS-MAY26', concepto:'Rodaje Hotel Florida Magaluf', importe:null, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2026-05-15', proveedor:'Laura Ribot', referencia:'LAU-MAY26', concepto:'Rodaje Zafiro', importe:null, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2025-12-15', proveedor:'Ismael Miranda', referencia:'ISM-DIC25', concepto:'Trabajo hotel Zafiro', importe:null, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2026-05-27', proveedor:'Euromoto Palma', referencia:'ALQ-MAY26', concepto:'Alquiler oficina mayo', importe:null, sociedad_codigo:'d', estado:'procesada' },
  { fecha_factura:'2026-05-26', proveedor:'Wayco Ruzafa', referencia:'2026-WRF18915', concepto:'Factura Wayco mayo', importe:null, sociedad_codigo:'x', estado:'pendiente' },
  { fecha_factura:'2026-05-26', proveedor:'Clicktotravel', referencia:'CT-244280', concepto:'Factura pendiente desde nov 2024', importe:37.43, sociedad_codigo:'x', estado:'alerta', alerta_texto:'Factura antigua sin pagar' },
  { fecha_factura:'2026-04-01', proveedor:'Pago Fraccionado', referencia:'PAG-97', concepto:'Pago mensual 97,58€', importe:97.58, sociedad_codigo:'x', estado:'procesada' },
  { fecha_factura:'2025-12-25', proveedor:'HBO Nordic', referencia:'HBO-DIC25', concepto:'HBO Max suscripción', importe:10.99, sociedad_codigo:'x', estado:'procesada' },
];

async function seed() {
  // Idempotent: requires a UNIQUE constraint on `referencia` (facturas_referencia_key).
  const { data, error } = await sb.from('facturas').upsert(FACTURAS, { onConflict: 'referencia' }).select();
  if (error) { console.error('ERROR:', error.message); process.exit(1); }
  console.log('Upserted:', data.length, 'facturas');
  const { count } = await sb.from('facturas').select('*', { count: 'exact', head: true });
  console.log('Total en BD:', count);
}
seed();
